import {
    Globe,
    Trophy,
    MapPin,
    Users,
    Droplet,
    HeartPulse
} from 'lucide-react'

export interface BlogPost {
    id: string
    title: string
    excerpt: string
    content: string
    date: string
    category: string
    image: string
    icon: any
    readTime: string
}

// This file is automatically generated from page.tsx posts
// To maintain, edit the posts in page.tsx and re-extract

export { Globe, Trophy, MapPin, Users, Droplet, HeartPulse }
